services:
  - type: web
    name: incassi-web
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python3 app.py"
    envVars:
      - key: SHARED_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
