create table if not exists public.players (
  id integer generated by default as identity primary key,
  name text not null,
  nickname text default '',
  phone text not null,
  username text default '',
  password_hash text default '',
  account_status text not null default 'approved',
  role text not null default 'Jolly',
  mascot text not null default 'jolly',
  mascot_name text default '',
  power integer not null default 3 check(power between 1 and 5),
  score integer not null default 0,
  goals integer not null default 0,
  assists integer not null default 0,
  wins integer not null default 0,
  matches integer not null default 0,
  reliability integer not null default 80,
  invite_token text not null unique,
  active integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id integer generated by default as identity primary key,
  title text not null,
  match_date text not null,
  location text not null,
  player_limit integer not null default 10,
  status text not null default 'open',
  team_a_name text default 'Squadra A',
  team_b_name text default 'Squadra B',
  team_a_score integer,
  team_b_score integer,
  created_at timestamptz not null default now()
);

create table if not exists public.match_players (
  match_id integer not null references public.matches(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  response text not null default 'invited',
  team text,
  goals integer not null default 0,
  assists integer not null default 0,
  cancelled_at timestamptz,
  penalty_points integer not null default 0,
  primary key(match_id, player_id)
);

create index if not exists idx_fantacalcetto_players_status
  on public.players(account_status, active);

create index if not exists idx_fantacalcetto_matches_date
  on public.matches(match_date desc);

create index if not exists idx_fantacalcetto_match_players_player
  on public.match_players(player_id);
